version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: picpay_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: picpay_db
    restart: always
    environment:
      MYSQL_DATABASE: picpay
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: picpay
      MYSQL_PASSWORD: picpay
    ports:
      - "3308:3306"  # Porta ajustada para evitar conflito local
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
